export interface CollegeSeedData {
  name: string;
  city: string;
  state: string;
}

export const COLLEGES: CollegeSeedData[] = [
  // IITs
  { name: 'Indian Institute of Technology Bombay', city: 'Mumbai', state: 'Maharashtra' },
  { name: 'Indian Institute of Technology Delhi', city: 'New Delhi', state: 'Delhi' },
  { name: 'Indian Institute of Technology Madras', city: 'Chennai', state: 'Tamil Nadu' },
  { name: 'Indian Institute of Technology Kanpur', city: 'Kanpur', state: 'Uttar Pradesh' },
  { name: 'Indian Institute of Technology Kharagpur', city: 'Kharagpur', state: 'West Bengal' },
  { name: 'Indian Institute of Technology Roorkee', city: 'Roorkee', state: 'Uttarakhand' },
  { name: 'Indian Institute of Technology Hyderabad', city: 'Hyderabad', state: 'Telangana' },
  { name: 'Indian Institute of Technology Guwahati', city: 'Guwahati', state: 'Assam' },
  { name: 'Indian Institute of Technology BHU Varanasi', city: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Indian Institute of Technology Bhubaneswar', city: 'Bhubaneswar', state: 'Odisha' },
  { name: 'Indian Institute of Technology Gandhinagar', city: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Indian Institute of Technology Indore', city: 'Indore', state: 'Madhya Pradesh' },
  { name: 'Indian Institute of Technology Jodhpur', city: 'Jodhpur', state: 'Rajasthan' },
  { name: 'Indian Institute of Technology Mandi', city: 'Mandi', state: 'Himachal Pradesh' },
  { name: 'Indian Institute of Technology Patna', city: 'Patna', state: 'Bihar' },
  { name: 'Indian Institute of Technology Ropar', city: 'Ropar', state: 'Punjab' },
  { name: 'Indian Institute of Technology Tirupati', city: 'Tirupati', state: 'Andhra Pradesh' },
  { name: 'Indian Institute of Technology Palakkad', city: 'Palakkad', state: 'Kerala' },
  { name: 'Indian Institute of Technology Dharwad', city: 'Dharwad', state: 'Karnataka' },
  { name: 'Indian Institute of Technology Bhilai', city: 'Bhilai', state: 'Chhattisgarh' },
  { name: 'Indian Institute of Technology Goa', city: 'Farmagudi', state: 'Goa' },
  { name: 'Indian Institute of Technology Jammu', city: 'Jammu', state: 'Jammu and Kashmir' },

  // NITs
  { name: 'National Institute of Technology Tiruchirappalli', city: 'Tiruchirappalli', state: 'Tamil Nadu' },
  { name: 'National Institute of Technology Karnataka', city: 'Surathkal', state: 'Karnataka' },
  { name: 'National Institute of Technology Rourkela', city: 'Rourkela', state: 'Odisha' },
  { name: 'National Institute of Technology Warangal', city: 'Warangal', state: 'Telangana' },
  { name: 'National Institute of Technology Calicut', city: 'Calicut', state: 'Kerala' },
  { name: 'Visvesvaraya National Institute of Technology', city: 'Nagpur', state: 'Maharashtra' },
  { name: 'Malaviya National Institute of Technology', city: 'Jaipur', state: 'Rajasthan' },
  { name: 'Motilal Nehru National Institute of Technology', city: 'Allahabad', state: 'Uttar Pradesh' },
  { name: 'Maulana Azad National Institute of Technology', city: 'Bhopal', state: 'Madhya Pradesh' },
  { name: 'National Institute of Technology Kurukshetra', city: 'Kurukshetra', state: 'Haryana' },
  { name: 'National Institute of Technology Silchar', city: 'Silchar', state: 'Assam' },
  { name: 'National Institute of Technology Durgapur', city: 'Durgapur', state: 'West Bengal' },
  { name: 'Dr. B. R. Ambedkar National Institute of Technology', city: 'Jalandhar', state: 'Punjab' },
  { name: 'Sardar Vallabhbhai National Institute of Technology', city: 'Surat', state: 'Gujarat' },
  { name: 'National Institute of Technology Patna', city: 'Patna', state: 'Bihar' },
  { name: 'National Institute of Technology Raipur', city: 'Raipur', state: 'Chhattisgarh' },
  { name: 'National Institute of Technology Srinagar', city: 'Srinagar', state: 'Jammu and Kashmir' },
  { name: 'National Institute of Technology Hamirpur', city: 'Hamirpur', state: 'Himachal Pradesh' },
  { name: 'National Institute of Technology Goa', city: 'Ponda', state: 'Goa' },
  { name: 'National Institute of Technology Jamshedpur', city: 'Jamshedpur', state: 'Jharkhand' },

  // BITS
  { name: 'BITS Pilani - Pilani Campus', city: 'Pilani', state: 'Rajasthan' },
  { name: 'BITS Pilani - Hyderabad Campus', city: 'Hyderabad', state: 'Telangana' },
  { name: 'BITS Pilani - Goa Campus', city: 'Sancoale', state: 'Goa' },

  // IIITs
  { name: 'International Institute of Information Technology Hyderabad', city: 'Hyderabad', state: 'Telangana' },
  { name: 'International Institute of Information Technology Bangalore', city: 'Bengaluru', state: 'Karnataka' },
  { name: 'Indraprastha Institute of Information Technology Delhi', city: 'New Delhi', state: 'Delhi' },
  { name: 'Indian Institute of Information Technology Allahabad', city: 'Prayagraj', state: 'Uttar Pradesh' },
  { name: 'Indian Institute of Information Technology Gwalior', city: 'Gwalior', state: 'Madhya Pradesh' },
  { name: 'Indian Institute of Information Technology Jabalpur', city: 'Jabalpur', state: 'Madhya Pradesh' },
  { name: 'Indian Institute of Information Technology Kancheepuram', city: 'Chennai', state: 'Tamil Nadu' },
  { name: 'Indian Institute of Information Technology Guwahati', city: 'Guwahati', state: 'Assam' },

  // Premier State & Central Universities / Institutes
  { name: 'Delhi Technological University', city: 'New Delhi', state: 'Delhi' },
  { name: 'Netaji Subhas University of Technology', city: 'New Delhi', state: 'Delhi' },
  { name: 'College of Engineering Guindy - Anna University', city: 'Chennai', state: 'Tamil Nadu' },
  { name: 'College of Engineering Pune', city: 'Pune', state: 'Maharashtra' },
  { name: 'Veermata Jijabai Technological Institute', city: 'Mumbai', state: 'Maharashtra' },
  { name: 'Jadavpur University - Faculty of Engineering', city: 'Kolkata', state: 'West Bengal' },
  { name: 'Punjab Engineering College', city: 'Chandigarh', state: 'Chandigarh' },
  { name: 'Institute of Chemical Technology', city: 'Mumbai', state: 'Maharashtra' },
  { name: 'Jawaharlal Nehru Technological University Hyderabad', city: 'Hyderabad', state: 'Telangana' },
  { name: 'Osmania University College of Engineering', city: 'Hyderabad', state: 'Telangana' },
  { name: 'Andhra University College of Engineering', city: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { name: 'Harcourt Butler Technical University', city: 'Kanpur', state: 'Uttar Pradesh' },

  // Premier Private Universities & Autonomous Colleges
  { name: 'Vellore Institute of Technology', city: 'Vellore', state: 'Tamil Nadu' },
  { name: 'VIT Chennai', city: 'Chennai', state: 'Tamil Nadu' },
  { name: 'SRM Institute of Science and Technology', city: 'Kattankulathur', state: 'Tamil Nadu' },
  { name: 'Manipal Institute of Technology', city: 'Manipal', state: 'Karnataka' },
  { name: 'Thapar Institute of Engineering and Technology', city: 'Patiala', state: 'Punjab' },
  { name: 'PSG College of Technology', city: 'Coimbatore', state: 'Tamil Nadu' },
  { name: 'M. S. Ramaiah Institute of Technology', city: 'Bengaluru', state: 'Karnataka' },
  { name: 'R.V. College of Engineering', city: 'Bengaluru', state: 'Karnataka' },
  { name: 'BMS College of Engineering', city: 'Bengaluru', state: 'Karnataka' },
  { name: 'PES University', city: 'Bengaluru', state: 'Karnataka' },
  { name: 'SSN College of Engineering', city: 'Chennai', state: 'Tamil Nadu' },
  { name: 'Chaitanya Bharathi Institute of Technology', city: 'Hyderabad', state: 'Telangana' },
  { name: 'Vasavi College of Engineering', city: 'Hyderabad', state: 'Telangana' },
  { name: 'VNR Vignana Jyothi Institute of Engineering and Technology', city: 'Hyderabad', state: 'Telangana' },
  { name: 'Gokaraju Rangaraju Institute of Engineering and Technology', city: 'Hyderabad', state: 'Telangana' },
  { name: 'Kalinga Institute of Industrial Technology', city: 'Bhubaneswar', state: 'Odisha' },
  { name: 'Siksha O Anusandhan University', city: 'Bhubaneswar', state: 'Odisha' },
  { name: 'Amrita School of Engineering', city: 'Coimbatore', state: 'Tamil Nadu' },
  { name: 'SASTRA Deemed University', city: 'Thanjavur', state: 'Tamil Nadu' },
  { name: 'Thiagarajar College of Engineering', city: 'Madurai', state: 'Tamil Nadu' },
  { name: 'Coimbatore Institute of Technology', city: 'Coimbatore', state: 'Tamil Nadu' },
  { name: 'Kumaraguru College of Technology', city: 'Coimbatore', state: 'Tamil Nadu' },
  { name: 'Bannari Amman Institute of Technology', city: 'Sathyamangalam', state: 'Tamil Nadu' },
  { name: 'Kongu Engineering College', city: 'Perundurai', state: 'Tamil Nadu' },
  { name: 'Sri Sivasubramaniya Nadar College of Engineering', city: 'Kalavakkam', state: 'Tamil Nadu' },
  { name: 'Dwarkadas J. Sanghvi College of Engineering', city: 'Mumbai', state: 'Maharashtra' },
  { name: 'K. J. Somaiya College of Engineering', city: 'Mumbai', state: 'Maharashtra' },
  { name: 'Sardar Patel Institute of Technology', city: 'Mumbai', state: 'Maharashtra' },
  { name: 'Vishwakarma Institute of Technology', city: 'Pune', state: 'Maharashtra' },
  { name: 'Maharashtra Institute of Technology', city: 'Pune', state: 'Maharashtra' },
  { name: 'Walchand College of Engineering', city: 'Sangli', state: 'Maharashtra' },
  { name: 'KLE Technological University', city: 'Hubballi', state: 'Karnataka' },
  { name: 'Siddaganga Institute of Technology', city: 'Tumakuru', state: 'Karnataka' },
  { name: 'BMS Institute of Technology and Management', city: 'Bengaluru', state: 'Karnataka' },
  { name: 'Dayananda Sagar College of Engineering', city: 'Bengaluru', state: 'Karnataka' },
  { name: 'Nitte Meenakshi Institute of Technology', city: 'Bengaluru', state: 'Karnataka' },
  { name: 'New Horizon College of Engineering', city: 'Bengaluru', state: 'Karnataka' },
  { name: 'Sir M. Visvesvaraya Institute of Technology', city: 'Bengaluru', state: 'Karnataka' },
  { name: 'The National Institute of Engineering', city: 'Mysuru', state: 'Karnataka' },
  { name: 'Sri Jayachamarajendra College of Engineering', city: 'Mysuru', state: 'Karnataka' },
  { name: 'Gayatri Vidya Parishad College of Engineering', city: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { name: 'Sagi Rama Krishnam Raju Engineering College', city: 'Bhimavaram', state: 'Andhra Pradesh' },
  { name: 'Velagapudi Ramakrishna Siddhartha Engineering College', city: 'Vijayawada', state: 'Andhra Pradesh' },
  { name: 'G. Pulla Reddy Engineering College', city: 'Kurnool', state: 'Andhra Pradesh' },
  { name: 'Madanapalle Institute of Technology and Science', city: 'Madanapalle', state: 'Andhra Pradesh' },
  { name: 'L.D. College of Engineering', city: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Nirma University - Institute of Technology', city: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Pandit Deendayal Energy University', city: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Dhirubhai Ambani Institute of Information and Communication Technology', city: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Birla Institute of Technology Mesra', city: 'Ranchi', state: 'Jharkhand' },
  { name: 'Heritage Institute of Technology', city: 'Kolkata', state: 'West Bengal' },
  { name: 'Institute of Engineering and Management', city: 'Kolkata', state: 'West Bengal' },
  { name: 'Haldia Institute of Technology', city: 'Haldia', state: 'West Bengal' },
  { name: 'National Institute of Foundry and Forge Technology', city: 'Ranchi', state: 'Jharkhand' },

  // Generic fallback entry
  { name: 'Other', city: 'Other', state: 'Other' },
];
